CREATE USER BKH_ADM WITH
PASSWORD 'bkh_admn'
CONNECTION LIMIT 20
VALID UNTIL 'infinity';

GRANT ALL PRIVILEGES ON SCHEMA public TO BKH_ADM;
GRANT ALL PRIVILEGES ON SCHEMA BKH_ADM TO BKH_ADM;
SET search_path TO BKH_ADM,public;

CREATE USER MANUT_BKH WITH
CONNECTION LIMIT 20
VALID UNTIL 'infinity'
PASSWORD 'manut_bkh';

GRANT USAGE ON SCHEMA public TO MANUT_BKH;
GRANT USAGE ON SCHEMA BKH_ADM TO MANUT_BKH;

ALTER DEFAULT PRIVILEGES IN SCHEMA BKH_ADM GRANT ALL PRIVILEGES ON TABLES TO BKH_ADM;
ALTER DEFAULT PRIVILEGES IN SCHEMA BKH_ADM GRANT ALL PRIVILEGES ON SEQUENCES TO BKH_ADM;
ALTER DEFAULT PRIVILEGES IN SCHEMA BKH_ADM GRANT ALL PRIVILEGES ON FUNCTIONS TO BKH_ADM;
ALTER ROLE BKH_ADM SET search_path TO BKH_ADM,public;

ALTER DEFAULT PRIVILEGES IN SCHEMA BKH_ADM GRANT SELECT ON TABLES TO MANUT_BKH;
ALTER DEFAULT PRIVILEGES IN SCHEMA BKH_ADM GRANT SELECT, USAGE ON SEQUENCES TO MANUT_BKH;
ALTER DEFAULT PRIVILEGES IN SCHEMA BKH_ADM GRANT EXECUTE ON FUNCTIONS TO MANUT_BKH;