INSERT INTO CATEGORIA (id,nome_categoria) VALUES (66,'acadêmico');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (61,'ação');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (55,'adulto');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (49,'áfrica austral');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (68,'animal');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (73,'antologia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (19,'apocalíptico');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (46,'arte');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (32,'arte sequencial');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (64,'audiobook');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (26,'auto ajuda');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (31,'aventura');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (35,'biografia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (56,'ciência');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (7,'clássico');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (58,'contemporâneo');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (16,'cristão');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (52,'cultural');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (41,'curtas');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (30,'educação');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (38,'erótico');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (60,'escrita');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (13,'espaço');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (33,'espiritual');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (28,'esportes e jogos');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (75,'fadas');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (2,'fantasia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (76,'fantasia heróica');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (63,'feminismo');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (1,'ficção');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (48,'ficção adulta');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (72,'ficção alternativa');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (6,'ficção científica');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (20,'ficção cristã');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (51,'ficção especulativa');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (62,'ficção literária');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (54,'ficção realista');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (42,'filosofia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (17,'games');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (14,'gótico');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (39,'guerra');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (18,'história');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (45,'histórico');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (23,'hq');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (65,'humanas');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (44,'humor');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (47,'inspiração');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (9,'jovem adulto');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (11,'juvenil');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (12,'lgbt');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (74,'linguagem');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (10,'literatura');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (29,'literatura europeia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (57,'mágica realista');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (25,'manga');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (50,'mídias sociais');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (5,'mistério');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (59,'mitologia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (36,'moderno');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (80,'morte');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (37,'música');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (70,'negócios');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (77,'novela');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (67,'novo adulto');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (22,'paranormal');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (34,'poesia');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (43,'politica');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (79,'polpa');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (21,'prêmios hugo');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (24,'realista');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (69,'recontos');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (27,'relacionamentos');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (8,'romance');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (78,'romano');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (40,'rpg');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (4,'suspense');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (53,'teatro');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (3,'terror');
INSERT INTO CATEGORIA (id,nome_categoria) VALUES (71,'transmorfo');
